### ISSUE TITLE
potential conflicting code issue

### ISSUE THREAD

**Issue by BlaisinX** [HardWare68/Programming-Thing#14]
okay so i think i should have my own branch to upload my codes to so that we dont accidentally overwrite each others code by merging

**Comment by HardWare68** [comment]
okay so yeah, i think we should all have separate branches, and then the "master" branch is just so we're all on the same page or something. otherwise, we work on a thing in the branch, and then yeah. i dont know

**Comment by BlaisinX** [comment]
okay just don't pull request and we'll be fine

**Comment by HardWare68** [comment]
so like, you open the pull request when you want to merge it, and uhh yeah. sounds good i think
