### ISSUE TITLE
add like a log or something

### ISSUE THREAD

**Issue by BlaisinX** [HardWare68/Programming-Thing#22]
gonna store long text in variables and call it with an input function

**Comment by HardWare68** [comment]
wait what the heck are you wanting to do here?

**Comment by BlaisinX** [comment]
ask user for number
give user stored text based on the number they inputted

**Comment by HardWare68** [comment]
oh, i think i could do that pretty easy with JSON, just simply say "what you wanna see" then have an array inside the file with a bunch of messages

**Comment by BlaisinX** [comment]
bit heroes familiar stat calculator 2

**Comment by HardWare68** [comment]
if hero == bit then yeah

**Comment by BlaisinX** [comment]
https://www.khanacademy.org/computer-programming/bit-heroes-familiar-stats-calculator/6296420586455040

**Comment by HardWare68** [comment]
yeah that works as well, a little bit ugly in my opinion, but oh well lol

**Comment by BlaisinX** [comment]
I'm stupid and I'm completely okay with that

**Comment by HardWare68** [comment]
look pal, I'm the only one around here allowed to write any spaghetti code. I don't care that you may be going into cooking in the future, you're gonna keep your code spaghetti free. If I see even a single drop of marinara sauce within this code that didn't come from me, there's going to be a real problem buddy.

**Comment by BlaisinX** [comment]
Haha noodle go brr

**Comment by HardWare68** [comment]
![Uploading **image.png…]()**
No you can't just upload spaghetti code! It makes the code look bad and it becomes unreadable!

**Comment by HardWare68** [comment]
![image](https://user-images.githubusercontent.com/47306310/107643855-ad89d780-6c44-11eb-966e-86f94a4935b6.png)
No you can't just write spaghetti code! It makes the code look bad and unreadable!

**Comment by BlaisinX** [comment]
![weknow](https://user-images.githubusercontent.com/74415050/107644024-e629b100-6c44-11eb-8947-b1cdd8e805d2.PNG)
No.

**Comment by HardWare68** [comment]
whatever you do, do not look at the if statements in tictactoe.js
Worst mistake of my life!

**Comment by BlaisinX** [comment]
_leaves the github repository_

**Comment by HardWare68** [comment]
wait hold on, i promise some day i will make it look like not garbage

**Comment by BlaisinX** [comment]
it looks awful oh my god

**Comment by HardWare68** [comment]
im sorry, please do not bully me about it ):
someday it will be not garage ):

**Comment by BlaisinX** [comment]
it's okay i'm worse
look at my old khan academy programs

**Comment by HardWare68** [comment]
sans cereal
sans cereal

**Comment by BlaisinX** [comment]
`console.log("What's nine plus ten?");`

**Comment by HardWare68** [comment]
`var result = 21;`

**Comment by BlaisinX** [comment]
`console.log("You stupid");`

**Comment by HardWare68** [comment]
`var audio = new audio('vineboom.mp3');
audio.play();`

**Comment by BlaisinX** [comment]
I changed my mind, closing this
