### ISSUE TITLE
I may be stupid

### ISSUE THREAD

**Issue by BlaisinX** [HardWare68/Programming-Thing#42]
but how does one use the test.js file

**Comment by HardWare68** [comment]
so thats for travis.ci, it tests all the functions to make sure they work.

first it imports all the testdata from the test data json file thingy, and then it goes through and tests each function with the input and checks to make sure it is the expected output. 

so if you wish to start testing your jazz:
1.) Set up your test data in the JSON file
2.) Implement the testing thingy in test.js
3.) ???
4.) Profit

**Comment by BlaisinX** [comment]
okay, how do I run it

**Comment by HardWare68** [comment]
If you are using repl.it, go to "Shell," then type `node test.js`.

**Comment by BlaisinX** [comment]
okay thanks
