### ISSUE TITLE
DO STUFF ON YOUR BRANCH BLAiSIN

### ISSUE THREAD

**Issue by HardWare68** [HardWare68/Programming-Thing#55]
PUT THE WEBHOOK IN THERE, AND UPDATE THAT STUFF!?!?!?!?!?!?!?!?!!!?!!?!?!?!?!?!??!!?@!?@/21/12/1/2?

**Comment by BlaisinX** [comment]
![weknow](https://user-images.githubusercontent.com/74415050/111781556-a6329b00-888e-11eb-967b-587e5308d550.PNG)
No.

**Comment by HardWare68** [comment]
![image](https://user-images.githubusercontent.com/47306310/111782013-e85bdc80-888e-11eb-8683-b147165f94a5.png)
You can't just ignore your branch! You need to update it so that way you are working with the most recent code! If you don't update it, it'll cause more problems later on down the line!

**Comment by BlaisinX** [comment]
![ttrol](https://user-images.githubusercontent.com/74415050/111782134-0e817c80-888f-11eb-8c3a-468bbb916e38.png)
Problem?

**Comment by HardWare68** [comment]
ok but like for real, do that. i linked up GitHub to replit so that way pushing to github wouldn't be as much of a pain for you, so yeah

**Comment by BlaisinX** [comment]
if I think of anything to do okay

**Comment by HardWare68** [comment]
just do the two pull requests that i opened on your branch
please?
🥺 👉 👈
