### ISSUE TITLE
calsh of clanb

### ISSUE THREAD

**Issue by HardWare68** [HardWare68/Programming-Thing#56]
make class of clans

**Comment by BlaisinX** [comment]
barboolean

**Comment by HardWare68** [comment]
make sure you program in programming war guys!

**Comment by BlaisinX** [comment]
please stop rushing your repository, upgrade your firewalls first im begging you

**Comment by HardWare68** [comment]
*upgrades my repository's main code without upgrading anything else like a boss*

**Comment by BlaisinX** [comment]
Braps moment

**Comment by HardWare68** [comment]
alright, ive come to make an announcement. we are no longer offering support for clash of clans. instead, we're going to shift our focus onto hay day

thank you for your continued support

**Comment by BlaisinX** [comment]
goodbye barboolean

**Comment by HardWare68** [comment]
var chicken = "Cock-a-doodle-doo!";
